services:
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    container_name: tstweb-frontend
    ports:
      - "8080:80"
    networks:
      - tstweb_net
  backend:
    build:
      dockerfile: backend.Dockerfile
    container_name: tstweb-backend
    depends_on:
      - mysql
    ports:
      - "8000:80"
    networks:
      - tstweb_net
  mysql:
    build:
      dockerfile: mysql.Dockerfile
    container_name: tstweb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - tstweb_db_data:/var/lib/mysql
    networks:
      - tstweb_net
networks:
  tstweb_net:

volumes:
  tstweb_db_data:                   